services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-monitoring
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MY_HANGFIRE_CONNECTION_POSTGRES=${MY_HANGFIRE_CONNECTION_POSTGRES}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    ports:
      - "5000:8080" # API interna na porta 8080, exposta externamente na 5000 (opcional se tiver proxy)
    depends_on:
      - postgres
    networks:
      - internal

  postgres:
    image: postgres:16
    container_name: crypto-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "81:81"   # Painel admin do Nginx Proxy Manager
      - "443:443"
    volumes:
      - nginx-data:/data
      - nginx-letsencrypt:/etc/letsencrypt
    networks:
      - internal

volumes:
  postgres-data:
  nginx-data:
  nginx-letsencrypt:

networks:
  internal:
    driver: bridge
